# Generated by Django 4.1.7 on 2023-03-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userReg', '0002_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='character_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
